name: Electron Build and Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install --force
        

      - name: Build Electron
        run: |
          npm run build
          npm run packapp || true

      - name: Find exe files and zip
        run: |
          cd build
          Compress-Archive -Path .\*.exe -DestinationPath MyMusicApp.zip

      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(cat package.json | jq -r .version)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:          
          tag_name: v${{ steps.get_version.outputs.version }}  # 使用 package.json 中的版本号
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
         

      - name: Upload Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}              
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/MyMusicApp.zip # 指定二进制压缩文件路径
          asset_name: MyElectronMusicApp-${{ github.run_number }}.zip
          asset_content_type: application/zip

